[server]
headless = true
enableCORS = false
enableXsrfProtection = false
maxUploadSize = 50

[runner]
magicEnabled = false

[theme]
primaryColor = "#1A4D2E"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F5F5F5"
textColor = "#262730"
